services:
  # Zero Point Labs Next.js Application
  zeropoint-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeropoint-labs-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_APPWRITE_ENDPOINT=https://cloud.appwrite.io/v1
      - NEXT_PUBLIC_APPWRITE_PROJECT_ID=6861736a0007a58bac63
      - APPWRITE_API_KEY=${APPWRITE_API_KEY}
    env_file:
      - .env.local
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # GP Realty Cyprus Next.js Application (Only if the directory exists)
  # template-app:
  #   build:
  #     context: ../simple-template-first copy
  #     dockerfile: Dockerfile
  #   container_name: gprealty-cyprus-app
  #   restart: unless-stopped
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3001
  #   networks:
  #     - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: multi-site-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.bak:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    depends_on:
      - zeropoint-app
      # - template-app

  # Certbot for SSL
  certbot:
    image: certbot/certbot
    container_name: multi-site-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge 