services:
  # GP.Realty Cyprus Next.js Application
  gprealty-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gprealty-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_TELEMETRY_DISABLED=1
    expose:
      - "3001"
    networks:
      - gprealty-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: gprealty-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - gprealty-network
    depends_on:
      - gprealty-app

  # Certbot for SSL
  certbot:
    image: certbot/certbot
    container_name: gprealty-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  gprealty-network:
    driver: bridge 